export { OverviewTab } from './OverviewTab'
export { WorkflowTab } from './WorkflowTab'
export { DocumentsTab } from './DocumentsTab'
export { CommentsTab } from './CommentsTab'
export { ActivityTab } from './ActivityTab'
export { GatesTab } from './GatesTab'
export { PartnersTab } from './PartnersTab'
export { FinancialsTab } from './FinancialsTab'
export { CommsTab } from './CommsTab'
export { EditAssetModal } from './EditAssetModal'
export { SaveTemplateModal } from './SaveTemplateModal'
// Legacy — kept for standalone use outside asset detail
export { TasksTab } from './TasksTab'
export { MeetingsTab } from './MeetingsTab'
export { CommunicationsTab } from './CommunicationsTab'
